x-postgres-common: &postgres-common
  command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
  environment:
    POSTGRES_USER: ${USER}
    POSTGRES_HOST_AUTH_METHOD: trust
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  postgres14:
    <<: *postgres-common
    image: postgres:14-alpine
    container_name: pg_peek_postgres14
    ports:
      - "5440:5432"
    volumes:
      - postgres14_data:/var/lib/postgresql/data

  postgres15:
    <<: *postgres-common
    image: postgres:15-alpine
    container_name: pg_peek_postgres15
    ports:
      - "5441:5432"
    volumes:
      - postgres15_data:/var/lib/postgresql/data

  postgres16:
    <<: *postgres-common
    image: postgres:16-alpine
    container_name: pg_peek_postgres16
    ports:
      - "5442:5432"
    volumes:
      - postgres16_data:/var/lib/postgresql/data

  postgres17:
    <<: *postgres-common
    image: postgres:17-alpine
    container_name: pg_peek_postgres17
    ports:
      - "5443:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data

  postgres18:
    <<: *postgres-common
    image: postgres:18-alpine
    container_name: pg_peek_postgres18
    ports:
      - "5444:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql/data

volumes:
  postgres14_data:
  postgres15_data:
  postgres16_data:
  postgres17_data:
  postgres18_data:
