services:
  postgres16:
    image: postgres:16-alpine
    container_name: pg_peek_postgres16
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: pg_peek_development
    ports:
      - "5432:5432"
    volumes:
      - postgres16_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres17:
    image: postgres:17-alpine
    container_name: pg_peek_postgres17
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: pg_peek_development
    ports:
      - "5433:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres18:
    image: postgres:18beta1-alpine
    container_name: pg_peek_postgres18
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: pg_peek_development
    ports:
      - "5434:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres16_data:
  postgres17_data:
  postgres18_data:
